#ifndef LUNAFLUX_SERIAL_TRANSFER_TEST_REDIRECT_H
#define LUNAFLUX_SERIAL_TRANSFER_TEST_REDIRECT_H
#define lunaflux_cuda_streaming_create lunaflux_serial_test_streaming_create
#define lunaflux_cuda_streaming_close lunaflux_serial_test_streaming_close
#define lunaflux_cuda_streaming_enqueue lunaflux_serial_test_streaming_enqueue
#define lunaflux_cuda_streaming_record lunaflux_serial_test_streaming_record
#define lunaflux_cuda_streaming_poll lunaflux_serial_test_streaming_poll
#define lunaflux_cuda_streaming_drain lunaflux_serial_test_streaming_drain
#define lunaflux_cuda_streaming_reset lunaflux_serial_test_streaming_reset
#define lunaflux_cuda_streaming_host_copy lunaflux_serial_test_streaming_host_copy
#endif
