#ifndef LUNAFLUX_PROCESS_STATUS_H
#define LUNAFLUX_PROCESS_STATUS_H

enum {
  LF_PROCESS_OK = 0,
  LF_PROCESS_INVALID_STATE = 1,
  LF_PROCESS_TIMEOUT = 2,
  LF_PROCESS_CHANNEL_CLOSED = 3,
  LF_PROCESS_FAILED = 4,
  LF_PROCESS_PENDING = 5
};

#endif
