#ifndef LUNAFLUX_MONOTONIC_CLOCK_STATUS_H
#define LUNAFLUX_MONOTONIC_CLOCK_STATUS_H

enum {
  LF_MONOTONIC_CLOCK_OK = 0,
  LF_MONOTONIC_CLOCK_UNAVAILABLE = 1,
  LF_MONOTONIC_CLOCK_OUT_OF_RANGE = 2
};

#endif
